defaults:
  - featurizer: patch_cnn
  - decoder: channel_time_rope_transformer
  - head: mlp
  - _self_

_target_: emg2pose.models.modules.spatial_rope_former.SpatialRoPEFormer

num_channels: 16
embed_dim: 256
head:
  in_channels: 256
