_target_: egoemg.models.modules.resnet_vision.ResNetVisionPose

out_channels: 22
pretrained: true
freeze_backbone: false
backbone_type: resnet18  # resnet18 | resnet34 | resnet50
head_hidden: 512
head_dropout: 0.1
