_target_: emg2pose.models.modules.vit_vision.VisionViTPose

out_channels: 22
pretrained: true
freeze_backbone: false
backbone_type: vit_b_16  # vit_b_16 | vit_b_32 | vit_l_16 | vit_l_32 | vit_h_14
head_hidden: 512
head_dropout: 0.1
