# @package _global_
to_tensor:
  _target_: emg2pose.transforms.ExtractToTensor
  field: emg

transforms:
  train:
  - _target_: emg2pose.transforms.ExtractField
    field: emg
  - _target_: emg2pose.transforms.RotationAugmentation
    channel_dim: -1
  - _target_: emg2pose.transforms.RandomGain
    min_gain: 0.8
    max_gain: 1.25
    mask_prob: 0.5
    per_channel: true
    channel_dim: -1
  - _target_: emg2pose.transforms.ToFloatTensor
  - _target_: emg2pose.transforms.RandomChannelMask
    mask_prob: 0.3
    min_masked: 0
    max_masked: null
    channel_dim: -1
    mask_value: 0.0
  - _target_: emg2pose.transforms.RandomTimeMask
    max_mask_size: 800
    num_masks: 3
    min_mask_size: 0
    time_dim: 0
    mask_value: 0.0
  - _target_: emg2pose.transforms.RandomFrequencyMask
    max_mask_size: 128
    num_masks: 5
    min_mask_size: 0
    time_dim: 0
  - _target_: emg2pose.transforms.RandomGaussianNoise
    min_snr_db: 20
    max_snr_db: 30
    apply_prob: 0.7
    time_dim: 0
  val:
  - ${to_tensor}
  test: ${transforms.val}
