defaults:
  - _self_
  - datamodule: default
  - optimizer: adamw
  - lr_scheduler: cosine
  - data_split: full_split
  - transforms: rotation_augmentation
  - experiment: physiowave_temporal_regression
  - physiowave_module: temporal_regression

data_location: /home/xiziheng/develop/emg2pose/data/emg2pose_data

seed: 42
matmul_precision: null  # one of: highest, high, medium

batch_size: 32
num_workers: 4

train: True
eval: True
checkpoint: null

monitor_metric: val_loss
monitor_mode: min

loss_weights:
  mae: 1
  fingertip_distance: 0.01

trainer:
  max_epochs: 50
  devices: [0]
  log_every_n_steps: 1
  precision: 32
  enable_model_summary: False

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: 2
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    save_top_k: 3
    save_last: True
    verbose: True
    filename: "best-{monitor_metric:.4f}"
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    patience: 50
    check_on_train_epoch_end: False
    verbose: True

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}/seed=${seed}
  output_subdir: hydra_configs
  job:
    name: emg2pose_physiowave
    config:
      override_dirname:
        exclude_keys:
          - seed
