# @package _global_
dataset:
  train:
    # emg2pose (train split)
    - _target_: egoemg.datasets.emg2pose_dataset.Emg2PoseDataset
      root_dir: ${data_location}
      window_length: ${datamodule.window_length}
      stride: ${datamodule.stride}
      padding: ${datamodule.padding}
      jitter: true
      skip_ik_failures: ${datamodule.skip_ik_failures}
      allowed_splits: [train]

    # emg2qwerty (all sessions -> train)
    - _target_: egoemg.datasets.emg2qwerty_dataset.Emg2QwertyDataset
      root_dir: data/emg_corpus/emg2qwerty_v3
      window_length: ${datamodule.window_length}
      stride: ${datamodule.stride}
      padding: ${datamodule.padding}
      jitter: true

    # ninapro DB1 (all sessions -> train)
    - _target_: egoemg.datasets.ninapro_dataset.NinaproDB1Dataset
      root_dir: data/emg_corpus/Ninapro_relabeled_zarr/DB1
      window_length: ${datamodule.window_length}
      stride: ${datamodule.stride}
      padding: ${datamodule.padding}
      jitter: true
      return_joint_angles: true
      use_gesture_as_joint_angles: true
      return_gesture_labels: false

    # pimforce (all sessions -> train)
    - _target_: egoemg.datasets.pimforce_dataset.PimforceDataset
      root_dirs: [data/emg_corpus/PiMforce/pimforce_v3]
      window_start: 0
      window_stop: null
      window_stride: 1
      clip_to_valid: false
      pose_mode: last
      repeat_pose: true
      pose_in_degrees: true

  val:
    # emg2pose (val split only)
    - _target_: egoemg.datasets.emg2pose_dataset.Emg2PoseDataset
      root_dir: ${data_location}
      window_length: ${datamodule.val_test_window_length}
      stride: ${datamodule.val_test_stride}
      padding: ${datamodule.padding}
      jitter: false
      skip_ik_failures: ${datamodule.skip_ik_failures}
      allowed_splits: [val]

  test:
    # emg2pose (test split only)
    - _target_: egoemg.datasets.emg2pose_dataset.Emg2PoseDataset
      root_dir: ${data_location}
      window_length: ${datamodule.val_test_window_length}
      stride: ${datamodule.val_test_stride}
      padding: [0, 0]
      jitter: false
      skip_ik_failures: ${datamodule.skip_ik_failures}
      allowed_splits: [test]
