# @package _global_
dataset:
  train:
    - _target_: egoemg.datasets.pretrain_wrapper.PretrainWrapperDataset
      name: egoemg
      gesture_spaces: ${gesture_spaces}
      angle_dim: 22
      base:
        _target_: egoemg.datasets.egoemg_memmap_dataset.EgoEmgMemmapDataset
        memmap_dir: ${egoemg_memmap_dir}
        window_length: ${datamodule.window_length}
        stride: ${datamodule.stride}
        allowed_splits: [train]
        modalities: [emg, joint_angles, labels]
        target_hand: left
        emg_field_preference: filtered
        emg_layout: ${egoemg_emg_layout}
        emg2pose_channel_indices: ${egoemg_emg2pose_channel_indices}
        dataset_name: egoemg

    - _target_: egoemg.datasets.pretrain_wrapper.PretrainWrapperDataset
      name: egoemg
      gesture_spaces: ${gesture_spaces}
      angle_dim: 22
      base:
        _target_: egoemg.datasets.egoemg_memmap_dataset.EgoEmgMemmapDataset
        memmap_dir: ${egoemg_memmap_dir}
        window_length: ${datamodule.window_length}
        stride: ${datamodule.stride}
        allowed_splits: [train]
        modalities: [emg, joint_angles, labels]
        target_hand: right
        emg_field_preference: filtered
        emg_layout: ${egoemg_emg_layout}
        emg2pose_channel_indices: ${egoemg_emg2pose_channel_indices}
        dataset_name: egoemg

    - _target_: egoemg.datasets.pretrain_wrapper.PretrainWrapperDataset
      name: emg2pose
      gesture_spaces: ${gesture_spaces}
      angle_dim: 22
      base:
        _target_: egoemg.datasets.emg2pose_dataset.Emg2PoseDataset
        memmap_dir: ${data_root}/emg2pose_memmap
        window_length: ${datamodule.window_length}
        stride: ${datamodule.stride}
        padding: ${datamodule.padding}
        jitter: true
        skip_ik_failures: ${datamodule.skip_ik_failures}
        allowed_splits: [train]

  val:
    - _target_: egoemg.datasets.pretrain_wrapper.PretrainWrapperDataset
      name: egoemg
      gesture_spaces: ${gesture_spaces}
      angle_dim: 22
      base:
        _target_: egoemg.datasets.egoemg_memmap_dataset.EgoEmgMemmapDataset
        memmap_dir: ${egoemg_memmap_dir}
        window_length: ${datamodule.val_test_window_length}
        stride: ${datamodule.val_test_stride}
        allowed_splits: [val]
        modalities: [emg, joint_angles, labels]
        target_hand: left
        emg_field_preference: filtered
        emg_layout: ${egoemg_emg_layout}
        emg2pose_channel_indices: ${egoemg_emg2pose_channel_indices}
        dataset_name: egoemg

    - _target_: egoemg.datasets.pretrain_wrapper.PretrainWrapperDataset
      name: egoemg
      gesture_spaces: ${gesture_spaces}
      angle_dim: 22
      base:
        _target_: egoemg.datasets.egoemg_memmap_dataset.EgoEmgMemmapDataset
        memmap_dir: ${egoemg_memmap_dir}
        window_length: ${datamodule.val_test_window_length}
        stride: ${datamodule.val_test_stride}
        allowed_splits: [val]
        modalities: [emg, joint_angles, labels]
        target_hand: right
        emg_field_preference: filtered
        emg_layout: ${egoemg_emg_layout}
        emg2pose_channel_indices: ${egoemg_emg2pose_channel_indices}
        dataset_name: egoemg

    - _target_: egoemg.datasets.pretrain_wrapper.PretrainWrapperDataset
      name: emg2pose
      gesture_spaces: ${gesture_spaces}
      angle_dim: 22
      base:
        _target_: egoemg.datasets.emg2pose_dataset.Emg2PoseDataset
        memmap_dir: ${data_root}/emg2pose_memmap
        window_length: ${datamodule.val_test_window_length}
        stride: ${datamodule.val_test_stride}
        padding: ${datamodule.padding}
        jitter: false
        skip_ik_failures: ${datamodule.skip_ik_failures}
        allowed_splits: [val]

  test: []
