_target_: emg2pose.models.featurizers.patch_cnn.PatchCNNFeaturizer
patch_size: 100
pad_mode: drop
pool_type: mean
conv_blocks:
  - _target_: emg2pose.models.featurizers.patch_cnn.PatchCNNBlock
    in_channels: 1
    out_channels: 32
    kernel_size: 7
    stride: 2
    padding: 0
    activation: gelu
    pool_kernel_size: 3
  - _target_: emg2pose.models.featurizers.patch_cnn.PatchCNNBlock
    in_channels: 32
    out_channels: 96
    kernel_size: 5
    stride: 1
    padding: 0
    activation: gelu
    pool_kernel_size: 3
  - _target_: emg2pose.models.featurizers.patch_cnn.PatchCNNBlock
    in_channels: 96
    out_channels: 256
    kernel_size: 3
    stride: 1
    padding: 0
    activation: gelu
